.PHONY: clean All

All:
	@echo "----------Building project:[ Arkanoid - Debug ]----------"
	@cd "Arkanoid" && "$(MAKE)" -f  "Arkanoid.mk"
clean:
	@echo "----------Cleaning project:[ Arkanoid - Debug ]----------"
	@cd "Arkanoid" && "$(MAKE)" -f  "Arkanoid.mk" clean
