.PHONY: clean All

All:
	@echo "----------Building project:[ Tetris - Debug ]----------"
	@cd "Tetris" && "$(MAKE)" -f  "Tetris.mk"
clean:
	@echo "----------Cleaning project:[ Tetris - Debug ]----------"
	@cd "Tetris" && "$(MAKE)" -f  "Tetris.mk" clean
