.PHONY: clean All

All:
	@echo "----------Building project:[ DoodleJump - Debug ]----------"
	@cd "DoodleJump" && "$(MAKE)" -f  "DoodleJump.mk"
clean:
	@echo "----------Cleaning project:[ DoodleJump - Debug ]----------"
	@cd "DoodleJump" && "$(MAKE)" -f  "DoodleJump.mk" clean
